Vagrant.configure(2) do |config|
  config.vm.define "bionic" do |bionic|
    bionic.vm.box = "bento/ubuntu-18.04"
    bionic.vm.hostname = "bionic.local"
    bionic.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh"
  end

  config.vm.define "cent7" do |cent7|
    cent7.vm.box = "bento/centos-7.5"
    cent7.vm.hostname = "cent7.local"
    cent7.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh"

  end

end

